name: Build and Deploy ğŸš€

on: [push]

env:
  RED: \033[31m
  NORMAL: \033[0;39m

jobs:
  build-and-deploy:
    name: Build and Deploy ğŸš€
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3.5.0

      - name: Install and Build ğŸ”§ 
        run: |
          echo -e "$RED CONSTRUCCIÃ“N DE LA APP $NORMAL"
          npm install
          npm run build
          

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
